"""add_learned_knowledge_model_for_dynamic_rag

Revision ID: e403028533de
Revises: bc526d472a9e
Create Date: 2025-06-28 23:46:13.406386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e403028533de'
down_revision = 'bc526d472a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learnedknowledge',
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('knowledge_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('learned_from_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('superseded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learnedknowledge_department'), 'learnedknowledge', ['department'], unique=False)
    op.create_index(op.f('ix_learnedknowledge_title'), 'learnedknowledge', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learnedknowledge_title'), table_name='learnedknowledge')
    op.drop_index(op.f('ix_learnedknowledge_department'), table_name='learnedknowledge')
    op.drop_table('learnedknowledge')
    # ### end Alembic commands ###
